BoxLayoutEx:

<BoxLayoutEx>:
    orientation: "vertical"
    Button:
        text: "A"
        size_hint: 1, .5
        size: "100dp", "80dp"
        pos_hint: {"center_y": .5}
    BoxLayout:
        Button:
            text: "C"
        Button:
            text: "D"
        Button:
            text: "C"
        Button:
            text: "D"
    Button:
        text: "C"
    Label:
        text: "D"